@BASE_URL = http://localhost:5000

### auth register
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "username" : "bestZa",
    "email" : "bestZa55@gmail.com",
    "firstName" : "bestkung",
    "lastName" : "lnwza",
    "password" : "@Concert123456",
    "confirmPassword" :"@Concert123456"
}

### auth login
POST  {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "username" : "fanboy01",
    "password" : "@Concert123456"
}

### test reset password 
POST {{BASE_URL}}/auth/reset-password
Content-Type: application/json

{
    "email" : "fanboy@gmail.com"
}