@BASE_URL = http://localhost:5000

### get all post
GET {{BASE_URL}}/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc2NTEyMjY0LCJleHAiOjE3NzcxMTcwNjR9.KkS_GbmWeSjmOlxi-71ePSA9SvchJ8yd_8c7gXEF5-M

### edit comment


### get a post
GET {{BASE_URL}}/posts/52
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc2ODI5NjU3LCJleHAiOjE3Nzc0MzQ0NTd9.Q-sUntxTQMVEE_F4m_VNeyAvzorW7cWQf_kYuEgDCPc

### create post
POST {{BASE_URL}}/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc1ODEwOTg0LCJleHAiOjE3NzY0MTU3ODR9.yeVuLZXpYrb8zzNZiloi-O1FjOO9Tb69O76WAvLURS8

{
    "title" : "Concert สนุกมากกกกก",
    "content" : "อยากให้จัดอีก"
}


### delete a post
DELETE {{BASE_URL}}/posts/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc1ODEwOTg0LCJleHAiOjE3NzY0MTU3ODR9.yeVuLZXpYrb8zzNZiloi-O1FjOO9Tb69O76WAvLURS8

### edit a post
PATCH  {{BASE_URL}}/posts/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc1ODEwOTg0LCJleHAiOjE3NzY0MTU3ODR9.yeVuLZXpYrb8zzNZiloi-O1FjOO9Tb69O76WAvLURS8

{
    "title" : "Concert สนุกมากกกกก",
    "content" : "อยากให้จัดอีก ได้ไหมมมมมมม"
}

### comment at post
POST {{BASE_URL}}/posts/9/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc1ODEwOTg0LCJleHAiOjE3NzY0MTU3ODR9.yeVuLZXpYrb8zzNZiloi-O1FjOO9Tb69O76WAvLURS8

{
    "content" : "ฉันเห็นด้วยยยยยยยย อยากให้จัดอีกมากๆๆๆ",
    "userId" : "3"
}

### Like Post
POST {{BASE_URL}}/posts/9/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc1ODEwOTg0LCJleHAiOjE3NzY0MTU3ODR9.yeVuLZXpYrb8zzNZiloi-O1FjOO9Tb69O76WAvLURS8

### unLike Post
DELETE  {{BASE_URL}}/posts/9/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc1ODEwOTg0LCJleHAiOjE3NzY0MTU3ODR9.yeVuLZXpYrb8zzNZiloi-O1FjOO9Tb69O76WAvLURS8

### edit comment
PATCH  {{BASE_URL}}/posts/9/comments/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc1ODEwOTg0LCJleHAiOjE3NzY0MTU3ODR9.yeVuLZXpYrb8zzNZiloi-O1FjOO9Tb69O76WAvLURS8

{
    "content" : "ฉันเห็นด้วยยยยยยยย อยากให้จัด อยากหาคนไปด้วยจัง",
    "userId" : "3"
}

### get all like
GET {{BASE_URL}}/posts/6/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc2NTEyMjY0LCJleHAiOjE3NzcxMTcwNjR9.KkS_GbmWeSjmOlxi-71ePSA9SvchJ8yd_8c7gXEF5-M

### edit comment
DELETE  {{BASE_URL}}/posts/3/comments/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc1ODEwOTg0LCJleHAiOjE3NzY0MTU3ODR9.yeVuLZXpYrb8zzNZiloi-O1FjOO9Tb69O76WAvLURS8
